### ISSUE TITLE
Example bookstore GRPC doesn't work in Kubernetes

### ISSUE THREAD

**Issue by samirbr** [GoogleCloudPlatform/python-docs-samples#1036]
I deployed GRPC Bookstore example `python-docs-samples/endpoints/bookstore-grpc` using `python-docs-samples/endpoints/kubernetes` config file. I have done all steps:
1. generate `out.pb`.
2. deployed the service config and http config to Service Manager.
3. deployed to GKE `bookstore-grpc` with transcoding (ESP).

I got no error in any of these steps.

It works when I initiate the server and use the client on my machine. It also works if I use the client from inside the container.

If I use the client passing the service external IP it fails. 
```
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.DEADLINE_EXCEEDED, Deadline Exceeded)>
```
It also fails when using `curl` and returns `????`.

Endpoints console doesn't register a single call to any of the endpoints.

There is anything I'm missing?

**Comment by samirbr** [comment]
I managed to make it work (HTTP/1.x and gRPC) adding extra ports as in [https://github.com/cloudendpoints/esp/blob/master/test/grpc/gke.yaml](https://github.com/cloudendpoints/esp/blob/master/test/grpc/gke.yaml).

Please, updated the documentation in `https://cloud.google.com/endpoints/docs/transcoding` and `https://cloud.google.com/endpoints/docs/get-started-grpc-compute-engine-docker#running_the_sample_api_and_esp_in_a_docker_container`.

**Comment by jonparrott** [comment]
@p-buse can you take a look at this?

**Comment by p-buse** [comment]
@samirbr could you please clarify what exactly you changed (and where) to make it work?

**Comment by samirbr** [comment]
* Service/Deployment configuration:

```
apiVersion: v1
kind: Service
metadata:
  name: <SERVICE NAME>
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: <SERVICE NAME>
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: <DEPLOYMENT NAME>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: <DEPLOYMENT NAME>
    spec:
      volumes:
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-S", "443",
          "-a", "grpc://127.0.0.1:<GRPC PORT>",
          "-s", "<ENDPOINT NAME>.endpoints.<PROJECT NAME>.cloud.goog",
          "-v", "<ENDPOINT RELEASE>",
        ]
        ports:
        - containerPort: 443        
        volumeMounts:
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
          readOnly: true
      - name: grpc
        image: gcr.io/<PROJECT ID>/<IMAGE NAME>:1.0
        ports:
        - containerPort: <GRPC PORT>
```

It also worked with other ports HTTP/1.x and HTTP/2.0:

```
apiVersion: v1
kind: Service
metadata:
  name: <SERVICE NAME>
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    name: http2
```

```
 containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-S", "443", # https
          "-P", "8080", # http2
          "-p", "8000", # http
          "-a", "grpc://127.0.0.1:<GRPC PORT>",
          "-s", "<ENDPOINT NAME>.endpoints.<PROJECT NAME>.cloud.goog",
          "-v", "<ENDPOINT RELEASE>",
        ]
        ports:
        - containerPort: 443
        - containerPort: 8000
        - containerPort: 8080
```

* GRPC server:

```
import grpc
from concurrent import futures

# ...

server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))

# ... add service as in bookshelf example

server.add_insecure_port('[::]:%s' % <GRPC PORT>)
server.start()

try:
    while True:
        time.sleep(env.ONE_DAY_IN_SECONDS)
except KeyboardInterrupt:
    server.stop(0)
```
I have a fully functional gRCP with JSON transcoding and HTTPS example working now.
