### ISSUE TITLE
Update GAE Standard BQ sample to use google-cloud liibarary

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/python-docs-samples#1360]
The doc example for [GAE Standard + BQ](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard/bigquery)  currently uses the older Google API Client Libraries.

Suggest updating the docs to show google cloud library examples.

eg, a basic example

```bash
virtualenv env
source env/bin/activate
pip install -t lib google-cloud-bigquery
```

- app.yaml:
```yaml
runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.*
  script: default.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: django
  version: latest
- name: ssl
  version: latest

env_variables:
   GAE_USE_SOCKETS_HTTPLIB : 'true'
```

- appengine_config.py

```python
import os
import sys

from google.appengine.ext import vendor
vendor.add('lib')
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))
```

- default.py

```python
#!/usr/bin/python

import os
import sys

from google.appengine.ext import webapp

from google.cloud import bigquery
from google.cloud.bigquery import Dataset

class MainPageTemplate(webapp.RequestHandler):

    def get(self):
      c=''
      client = bigquery.Client()      
      QUERY = (
          'SELECT name FROM `bigquery-public-data.usa_names.usa_1910_2013` '
          'WHERE state = "TX" '
          'LIMIT 100')
      query_job = client.query(QUERY)
      rows = query_job.result()

      for row in rows:
          c = c + str(row.name) + '\n'
      self.response.headers["Content-Type"] = "text/plain"
      self.response.set_status(200)
      self.response.out.write(c)

application = webapp.WSGIApplication([('/', MainPageTemplate)], debug=True)
```
