### ISSUE TITLE
Could not connect to server: No such file or directory. PostgreSQL--> CloudSQL connection Error on Google App Engine

### ISSUE THREAD

**Issue by SohaibShafiq1** [GoogleCloudPlatform/python-docs-samples#5680]
Is the server running locally and accepting connections on Unix domain socket "/cloudsql/connection-name/.s.PGSQL.5431"? Whenever i deploy and login for superuser, i recieve this error.
 **My app.yaml:**
```
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT core.wsgi

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 8
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
  target_concurrent_requests: 100

beta_settings:
  cloud_sql_instances: <connection-name>
runtime_config:
  python_version: 3
```
**My Settings.py:**
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD')
    }
}
DATABASES['default']['HOST'] = '/cloudsql/<connection-name>'
if os.getenv('GAE_INSTANCE'):
    pass
else:
    DATABASES['default']['HOST'] = '127.0.0.1'

STATIC_URL = config('STATIC_URL')
STATIC_ROOT='static'
AUTH_USER_MODEL = 'users.NewUser'
MEDIA_URL='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
```
I Run cloud_sql_proxy.exe file as well on port 5431.
`cloud_sql_proxy.exe -instances="<connection-name>"=tcp:5431`
Deployment is successful but database connection is a problem. **What is the solution for that.**
