### ISSUE TITLE
How to push only certain files to google function from repo using cloudbuild.yaml

### ISSUE THREAD

**Issue by bhandari-nitin** [GoogleCloudPlatform/python-docs-samples#5870]
## Describe the issue

Directory Structure: I have a repository, that contains 4 directories and cloudbuild.yaml and a README.md and a .pre-commit-cofig.yaml files out of which one directory contains the code that I want to be uploaded to the google function via a GCP trigger.

So far, I got it to work if I have cloudbuild.yaml file and the main.py file in the root directory, and that uploads all the remaining directories as well.

Issues:

1. How do I give the path of the function if it's in the directory and not in the root folder. I tried using the source flag with local file path but didn't work 
2. How do I upload only the required code directory to the google cloud function and not all of the code?

**Comment by bhandari-nitin** [comment]
Here's the contents of cloudbuild.yaml:

`steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '${_CF_NAME}', '--trigger-http', '--entry-point', 'main', '--runtime', 'python38', '--allow-unauthenticated']`

**Comment by ace-n** [comment]
Hi @bhandari-nitin 

Have you tried using the `dir` argument in `cloudbuild.yaml`?

```
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '${_CF_NAME}', '--trigger-http', '--entry-point', 'main', '--runtime', 'python38', '--allow-unauthenticated']
  dir: 'path/to/your/function'
```

You can find more information on this argument [here](https://cloud.google.com/build/docs/build-config#dir).

**Comment by bhandari-nitin** [comment]
Hi @ace-n ,

- Here's  my repo for reference: [gcp_functions](https://github.com/bhandari-nitin/gcp_functions)

- And here's the cloudbuild.yaml in the root dir, where as the function source is in gcp_func: 

```
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', '${_CF_NAME}', '--trigger-http', '--entry-point', 'main', '--runtime', 'python38', '--allow-unauthenticated']
  dir: 'gcp_func/main'
```

- And still got the error:

```
ERROR: build step 0 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1
ERROR
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: Build error details not available. Please check the logs at https://console.cloud.google.com/logs/viewer?project=sd-uber-dev-oyqb&advancedFilter=resource.type%3Dbuild%0Aresource.labels.build_id%3D59bed12b-f5dc-4bd8-8984-a25526195818%0AlogName%3Dprojects%2Fsd-uber-dev-oyqb%2Flogs%2Fcloudbuild
.............failed.
```

Is the path okay?
